"""
PII report generator - creates markdown reports from PII analysis.
"""

from pathlib import Path
from typing import Dict
from datetime import datetime

from mongo_replication.engine.pii import CollectionPIIAnalysis


def generate_pii_report(
    job_id: str,
    pii_analyses: Dict[str, CollectionPIIAnalysis],
    output_path: Path,
) -> None:
    """
    Generate a markdown PII analysis report.

    Args:
        job_id: Job identifier
        pii_analyses: Dictionary mapping collection names to PII analyses
        output_path: Path to write the markdown report
    """
    lines = []

    # Header
    lines.append(f"# PII Analysis Report: {job_id}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    # Summary
    total_collections = len(pii_analyses)
    collections_with_pii = sum(1 for a in pii_analyses.values() if a.has_pii)
    total_pii_fields = sum(a.pii_field_count for a in pii_analyses.values())

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total Collections:** {total_collections}")
    lines.append(f"- **Collections with PII:** {collections_with_pii}")
    lines.append(f"- **Total PII Fields:** {total_pii_fields}")
    lines.append("")

    # Collections with PII
    if collections_with_pii > 0:
        lines.append("## Collections with PII")
        lines.append("")

        # Sort collections by PII field count (descending)
        sorted_collections = sorted(
            [(name, analysis) for name, analysis in pii_analyses.items() if analysis.has_pii],
            key=lambda x: x[1].pii_field_count,
            reverse=True,
        )

        for collection_name, analysis in sorted_collections:
            lines.append(f"### {collection_name}")
            lines.append("")
            lines.append(f"**Samples Analyzed:** {analysis.total_samples}")
            lines.append("")

            if analysis.fields_with_pii:
                lines.append(
                    "| Field | Entity Type | Strategy | Prevalence | Avg Confidence | Detections |"
                )
                lines.append(
                    "|-------|-------------|----------|------------|----------------|------------|"
                )

                # Sort fields by prevalence (descending)
                sorted_fields = sorted(
                    analysis.fields_with_pii,
                    key=lambda x: x.prevalence_pct,
                    reverse=True,
                )

                for field_stat in sorted_fields:
                    lines.append(
                        f"| `{field_stat.field_path}` "
                        f"| {field_stat.entity_type} "
                        f"| `{field_stat.suggested_strategy}` "
                        f"| {field_stat.prevalence_pct:.1f}% "
                        f"| {field_stat.avg_confidence:.2f} "
                        f"| {field_stat.detections}/{field_stat.total_samples} |"
                    )

                lines.append("")

    # Collections without PII
    collections_without_pii = [
        name for name, analysis in pii_analyses.items() if not analysis.has_pii
    ]

    if collections_without_pii:
        lines.append("## Collections without PII")
        lines.append("")

        for collection_name in sorted(collections_without_pii):
            lines.append(f"- `{collection_name}`")

        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*This report was generated by the MongoDB Replication Tool.*")
    lines.append("")

    # Write to file
    output_path.write_text("\n".join(lines))
